### PR TITLE
Optimization in Ubuntu or debian Images

### PR DESCRIPTION
**Pull request by Rajpratik71**
Major Changes No 1 : debian package manager tweaks

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Major Changes No 2 : added packages apt-utils ca-certificates

Because build is 

1.  Slow and in log it is showing because "apt-utils" not installed 

2. to avoid build to exits with error without having certificate in wget, curl, git etc

### CODE REVIEW

**Comment by Rajpratik71** [comment]
@willnorris @sirdarckcat @cdibona @stephenR  requesting review

**Comment by sirdarckcat** [comment]
These tasks are frozen. If the current version works, I think we should keep it as is, as to avoid making accidental breaking changes.

**Comment by Rajpratik71** [comment]
this pr contain optimization for Docker images , which results in smaller download, pull and build time . 

This things are good in time and size perspective.

**Comment by sirdarckcat** [comment]
I don't know if any of the challenges use the recommended packages, we would need to test them all to make sure they work after the change, and if something breaks the authors won't necessarily be able to fix it now.

as such, these Dockerfiles are technically frozen, since any change we make is likely to cause issues we don't know how to fix.

**Pull request closed without merging**
